<script setup lang="ts">
import { computed } from 'vue'

import { Button } from '@/components/ui/button'
import type { CampaignBlogPost } from '@/types/campaign'

const props = defineProps<{
  blogs: CampaignBlogPost[]
  loadingBlogs?: boolean
  loadedBlogs?: boolean
  saving?: boolean
  previewLoading?: boolean
}>()

const emit = defineEmits<{
  (e: 'load' | 'publish-all' | 'unpublish-all'): void
  (e: 'preview' | 'publish' | 'unpublish', blog: CampaignBlogPost): void
}>()

const hasBlogs = computed(() => props.blogs.length > 0)

const formatBlogTimestamp = (blog: CampaignBlogPost) =>
  blog.published_at || blog.updated_at || blog.created_at || null

const getBlogPublicHref = (blog: CampaignBlogPost) => {
  if (blog.public_url) return blog.public_url

  if (blog.resource_path) {
    return `/resources/${blog.resource_path.replace(/^\/+/, '')}`
  }

  if (blog.slug) {
    return `/blog/${blog.slug}`
  }

  return ''
}
</script>

<template>
  <section class="border-border bg-background rounded-xl border p-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
      <div>
        <h2 class="text-foreground text-lg font-semibold">Generated Blogs</h2>
        <p class="mt-2 text-sm text-slate-500">
          Inspect blog posts generated by this campaign as publishing work completes.
        </p>
      </div>
      <div class="flex flex-wrap gap-2">
        <Button
          variant="secondary"
          :loading="loadingBlogs"
          :disabled="saving"
          @click="emit('load')"
        >
          {{ loadedBlogs ? 'Refresh' : 'Load blogs' }}
        </Button>
        <Button v-if="hasBlogs" variant="secondary" :disabled="saving" @click="emit('publish-all')">
          Publish All
        </Button>
        <Button
          v-if="hasBlogs"
          variant="secondary"
          :disabled="saving"
          @click="emit('unpublish-all')"
        >
          Unpublish All
        </Button>
      </div>
    </div>

    <ul v-if="blogs.length" class="mt-5 space-y-3">
      <li v-for="blog in blogs" :key="blog.id" class="border-border rounded-lg border px-4 py-3">
        <div class="flex flex-col gap-2">
          <div class="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between">
            <p class="text-sm font-semibold text-slate-800">
              {{ blog.title || 'Untitled blog post' }}
            </p>
            <p class="text-xs text-slate-500">
              {{
                formatBlogTimestamp(blog)
                  ? new Date(formatBlogTimestamp(blog)!).toLocaleString()
                  : 'Timestamp unavailable'
              }}
            </p>
          </div>
          <p class="text-xs text-slate-500">
            {{ blog.slug || blog.jurisdiction_name || blog.jurisdiction_id || blog.id }}
          </p>
          <p v-if="blog.meta_description" class="text-sm text-slate-600">
            {{ blog.meta_description }}
          </p>
          <div class="flex flex-wrap gap-2 pt-1">
            <Button
              variant="secondary"
              size="sm"
              :disabled="previewLoading"
              @click="emit('preview', blog)"
            >
              Preview
            </Button>
            <Button
              v-if="blog.is_published && getBlogPublicHref(blog)"
              as="a"
              variant="secondary"
              size="sm"
              :href="getBlogPublicHref(blog)"
              target="_blank"
              rel="noopener noreferrer"
            >
              Open Public Page
            </Button>
            <Button
              v-if="!blog.is_published"
              variant="secondary"
              size="sm"
              :disabled="saving"
              @click="emit('publish', blog)"
            >
              Publish
            </Button>
            <Button
              v-else
              variant="secondary"
              size="sm"
              :disabled="saving"
              @click="emit('unpublish', blog)"
            >
              Unpublish
            </Button>
          </div>
        </div>
      </li>
    </ul>

    <div v-else-if="loadingBlogs" class="mt-5 space-y-3">
      <div class="h-4 w-full animate-pulse rounded bg-slate-200" />
      <div class="h-4 w-2/3 animate-pulse rounded bg-slate-200" />
    </div>

    <p v-else class="mt-5 text-sm text-slate-500">
      {{
        loadedBlogs
          ? 'No generated blog posts were returned for this campaign.'
          : 'Load generated blog posts to inspect campaign publishing output.'
      }}
    </p>
  </section>
</template>
